NODE_ENV=testing \
SILENT_START=true \
APPLICATION_SERVER="$USERAPPSTORE_APPLICATION_SERVER" \
APPLICATION_SERVER_TOKEN="$USERAPPSTORE_APPLICATION_SERVER_TOKEN" \
DASHBOARD_SERVER="$USERAPPSTORE_DASHBOARD_SERVER" \
DOMAIN="$USERAPPSTORE_DOMAIN" \
STRIPE_KEY="$USERAPPSTORE_STRIPE_KEY" \
STRIPE_PUBLISHABLE_KEY="$USERAPPSTORE_STRIPE_PUBLISHABLE_KEY" \
SUBSCRIPTIONS_ENDPOINT_SECRET1="$USERAPPSTORE_SUBSCRIPTIONS_ENDPOINT_SECRET1" \
SUBSCRIPTIONS_ENDPOINT_SECRET2="$USERAPPSTORE_SUBSCRIPTIONS_ENDPOINT_SECRET2" \
CONNECT_ENDPOINT_SECRET="$USERAPPSTORE_CONNECT_ENDPOINT_SECRET" \
STRIPE_JS="false" \
IP="0.0.0.0" \
PAGE_SIZE=40 \
STORAGE_PATH="~/tmp/data1" \
mocha src/www --recursive --timeout 480000 --slow 4800000